on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test thangs
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Container build info step
        uses: ./ # Uses an action in the root directory
        id: build-deps
        with:
          image-name: Bananas
          release-infrastructure-branch: awesome-work
      # Use the output from the `hello` step
      - name: Get the name of container repo 
        run: echo "The repo name was ${{ steps.build-deps.outputs.container-repo }}"
      - name: Get the name of container repo owner
        run: echo "The repo name was ${{ steps.build-deps.outputs.container-repo-owner }}"
      - name: Get the name of container image
        run: echo "The image name was ${{ steps.build-deps.outputs.container-image-name }}"
      - name: Get the name of the infrastructure branch to be updated
        run: echo "The iname of the infrastructure branch to be updated ${{ steps.build-deps.outputs.infrastructure-branch }}"